import React,{useState} from "react";
import {createRoot} from "react-dom/client";
import "./index.css";
const products=[["VIP NetCraft","R$ 9,90","Vantagens essenciais para começar bem."],["VIP Elite","R$ 19,90","Mais benefícios e destaque no servidor."],["VIP Supremo","R$ 39,90","O pacote completo para o novo começo."],["Kit Inicial","R$ 4,90","Itens para acelerar seus primeiros passos."],["Kit Guerreiro","R$ 12,90","Equipamentos para entrar preparado."]];
function App(){
 const [nick,setNick]=useState(localStorage.getItem("ncbr_player")||""),[login,setLogin]=useState(!localStorage.getItem("ncbr_player")),[input,setInput]=useState(""),[tab,setTab]=useState("inicio"),[livepix,setLivepix]=useState(localStorage.getItem("ncbr_livepix")||""),[admin,setAdmin]=useState(localStorage.getItem("ncbr_admin")==="1"),[msg,setMsg]=useState("");
 const enter=()=>{const n=input.trim();if(n.length<3||n.length>32){setMsg("Digite um nickname entre 3 e 32 caracteres.");return}localStorage.setItem("ncbr_player",n);setNick(n);setLogin(false);setMsg("")};
 const buy=()=>{if(!livepix){setMsg("Configure o LivePix no Painel Admin.");setTab("admin");return}window.open(livepix,"_blank","noopener,noreferrer")};
 const save=()=>{localStorage.setItem("ncbr_livepix",livepix.trim());setMsg("Link do LivePix salvo.")};
 return <div className="app"><header><div className="brand" onClick={()=>setTab("inicio")}><b>N</b><strong>NETCRAFT<span>BR</span><small>Servidor Minecraft</small></strong></div><nav>{["inicio","servidor","vip","loja","eventos","comunidade"].map(x=><button className={tab===x?"on":""} onClick={()=>setTab(x)} key={x}>{x[0].toUpperCase()+x.slice(1)}</button>)}</nav><button className="user" onClick={()=>setTab(nick?"perfil":"inicio")}>{nick||"Entrar"}</button></header>
 {msg&&<div className="toast">{msg}<button onClick={()=>setMsg("")}>×</button></div>}
 <main>
 {tab==="inicio"&&<section className="hero"><div><label>NOVO COMEÇO • NETCRAFTBR</label><h1>COMECE O RESET<br/><span>COM VANTAGEM.</span></h1><p>Um novo começo está chegando. Prepare-se para jogar com seus amigos, participar de eventos e aproveitar tudo o que o NetCraftBR oferece.</p><button className="primary" onClick={()=>setTab("vip")}>Ver VIPs</button><button className="secondary" onClick={()=>setTab("servidor")}>Conhecer servidor</button></div><aside><i></i><small>STATUS DO SERVIDOR</small><h2>ONLINE</h2><p>NetCraftBR</p><code onClick={()=>navigator.clipboard?.writeText("BotuCraft.bed.net.br:21056")}>BotuCraft.bed.net.br:21056</code></aside></section>}
 {tab==="servidor"&&<Page title="Seu servidor, suas regras." sub="Um servidor focado em sobrevivência, economia, clãs, eventos e comunidade ativa."><div className="cards"><Card t="Sobrevivência" d="Construa, explore e evolua no seu ritmo."/><Card t="Economia" d="Compre, venda e movimente sua própria economia."/><Card t="Clãs e eventos" d="Compita, conquiste e participe das atividades." /></div><div className="connect"><small>ENDEREÇO</small><b>BotuCraft.bed.net.br:21056</b><button className="primary" onClick={()=>navigator.clipboard?.writeText("BotuCraft.bed.net.br:21056")}>Copiar IP</button></div></Page>}
 {tab==="vip"&&<Page title="Comece com vantagem." sub="Escolha seu VIP e aproveite o novo começo do NetCraftBR."><div className="products">{products.slice(0,3).map(p=><Product p={p} buy={buy} key={p[0]}/>)}</div></Page>}
 {tab==="loja"&&<Page title="Loja do NetCraftBR" sub="Itens para acelerar sua jornada."><div className="products">{products.slice(3).map(p=><Product p={p} buy={buy} key={p[0]}/>)}</div></Page>}
 {tab==="eventos"&&<Page title="O que está acontecendo." sub="Fique atento às próximas atividades."><div className="cards"><Card t="Evento de Abertura" d="Atividades especiais para marcar o novo começo."/><Card t="Desafio dos Jogadores" d="Mostre suas habilidades e dispute recompensas."/><Card t="Guerra de Clãs" d="Prepare seu clã para disputar territórios e posições." /></div></Page>}
 {tab==="comunidade"&&<Page title="Jogue junto." sub="Entre na comunidade e acompanhe as novidades."><div className="connect"><b>Discord NetCraftBR</b><span>O ponto de encontro dos jogadores.</span><button className="secondary">Em breve</button></div></Page>}
 {tab==="perfil"&&<Page title={"Olá, "+nick+"."} sub="Seu nickname está salvo neste navegador."><button className="secondary" onClick={()=>{localStorage.removeItem("ncbr_player");setNick("");setLogin(true)}}>Sair</button></Page>}
 {tab==="admin"&&<Page title="Painel Admin" sub="Configurações do site.">{!admin?<button className="primary" onClick={()=>{if(prompt("Senha do administrador")==="netcraftbr"){localStorage.setItem("ncbr_admin","1");setAdmin(true)}else setMsg("Senha incorreta.")}}>Entrar no painel</button>:<div className="admin"><h3>Pagamentos</h3><p>Link do LivePix usado nos botões de compra.</p><input value={livepix} onChange={e=>setLivepix(e.target.value)} placeholder="https://livepix.gg/..."/><button className="primary" onClick={save}>Salvar link</button><hr/><button className="secondary" onClick={()=>{localStorage.removeItem("ncbr_admin");setAdmin(false)}}>Sair do painel</button></div>}</Page>}
 </main><footer><b>NETCRAFTBR</b><span>Servidor Minecraft</span><span>© 2026 NetCraftBR</span></footer>
 {login&&<div className="overlay"><div className="modal"><b className="logo">N</b><h2>Entre no NetCraftBR</h2><p>Digite seu nickname do Minecraft para continuar.</p><input autoFocus value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&enter()} placeholder="Seu nickname"/>{msg&&<em>{msg}</em>}<button className="primary wide" onClick={enter}>Entrar</button></div></div>}
 </div>
}
function Page({title,sub,children}:{title:string;sub:string;children:React.ReactNode}){return <section className="page"><label>NETCRAFTBR</label><h1>{title}</h1><p className="sub">{sub}</p>{children}</section>}
function Card({t,d}:{t:string;d:string}){return <article className="card"><h3>{t}</h3><p>{d}</p></article>}
function Product({p,buy}:{p:string[];buy:()=>void}){return <article className="product"><small>NETCRAFTBR</small><h3>{p[0]}</h3><strong>{p[1]}</strong><p>{p[2]}</p><button className="primary wide" onClick={buy}>Comprar</button></article>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);